#! /usr/bin/bash
#
# get a tag as first argument and message id as second argument
#

# check if we have tag
if [[ $(notmuch search id:$2 and tag:$1) ]]; then
  echo "removing tag: $1 from id:$2"
  notmuch tag -$1 id:$2
else
  echo "adding tag: $1 from id:$2"
  notmuch tag +$1 id:$2
fi
